spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chattest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Xqf123

server:
  port: 7777

flyway:
  enabled: true

security:
  ignore: '/**'