spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 521234

server:
  port: 7777

flyway:
  enabled: true

#security:
#  ignore: '/**'